name: Health check

on:
  # Trigger the workflow on push events to the 'main' branch.
  push:
    branches:
      - main
  # Trigger the workflow on pull requests targeting the 'main' branch,
  # specifically when a pull request is opened or when changes are synchronized.
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  periodic_health_check:
    name: 'periodic health check'
    runs-on: ubuntu-20.04
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@b716ccb6645355dd9fcce8002ce460e5474f7f00
      with:
        url: https://full-stack-open-pokedex-bbck.onrender.com/health
        max-attempts: 3
        retry-delay: 60s
